import HeroSection from "./components/HomePage/HeroSection";


export const metadata = {
  title: 'Reshan - HomePage',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
      <div className="container mt-16 mx-auto">
        <HeroSection />
        {/* <AchievementsSection /> */}
      </div>
  );
}
